# Generated by Django 5.0.6 on 2024-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymarc', '0005_remove_exercisetraining_routine_remove_routine_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetraining',
            name='date_training',
            field=models.DateField(null=True),
        ),
    ]
