# Generated by Django 5.0.6 on 2024-06-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymarc', '0009_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayExercise',
            new_name='Workout',
        ),
    ]
