# Generated by Django 5.0.6 on 2024-06-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymarc', '0011_rename_exercisetraining_exerciseworkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='ExerciseTraining',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(blank=True, to='gymarc.muscle'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymarc.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('actual_reps', models.IntegerField()),
                ('actual_weight', models.FloatField()),
                ('completed_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_sets', to='gymarc.completedexercise')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymarc.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymarc.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='completedexercise',
            name='planned_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to='gymarc.plannedexercise'),
        ),
        migrations.CreateModel(
            name='PlannedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('min_reps', models.IntegerField()),
                ('max_reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('planned_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sets', to='gymarc.plannedexercise')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymarc.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('muscles', models.ManyToManyField(blank=True, to='gymarc.muscle')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='gymarc.weeklyroutine')),
            ],
        ),
        migrations.AddField(
            model_name='plannedexercise',
            name='routine_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_exercises', to='gymarc.weeklyroutineday'),
        ),
        migrations.DeleteModel(
            name='ExerciseWorkout',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
