# Generated by Django 5.0.6 on 2024-06-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymarc', '0014_weeklyroutineday_unique_routine_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_factor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
